apiVersion: v1
kind: Service
metadata:
  name: productos-service
  namespace: medisupply
spec:
  selector:
    app: productos-service
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productos-service
  namespace: medisupply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productos-service
  template:
    metadata:
      labels:
        app: productos-service
    spec:
      containers:
        - name: productos-service
          image: productos-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: database
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: postgres
